# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=12, unique=True)),
                ('title', models.TextField(default='')),
                ('image', models.URLField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('currency', models.CharField(default='', max_length=100)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(max_length=100, null=True)),
                ('manufacturer', models.CharField(max_length=100, null=True)),
                ('features', jsonfield.fields.JSONField()),
                ('itemURL', models.TextField(default='')),
                ('top_seller', models.BooleanField(default=True)),
                ('category', models.TextField(max_length=40, null=True)),
            ],
        ),
    ]
