# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20161018_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='editorial',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
