# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20161018_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='editorial',
            field=models.TextField(null=True),
        ),
    ]
