# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20161019_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='editorial_short',
            field=models.TextField(null=True),
        ),
    ]
